"""Initial migration with governance policies

Revision ID: a5b96c4ebf81
Revises: 
Create Date: 2026-04-09 10:34:27.193634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b96c4ebf81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_choices_choice_text'), table_name='choices')
    op.drop_index(op.f('ix_choices_id'), table_name='choices')
    op.drop_table('choices')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_text'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_deleteLater_description'), table_name='deleteLater')
    op.drop_index(op.f('ix_deleteLater_id'), table_name='deleteLater')
    op.drop_index(op.f('ix_deleteLater_name'), table_name='deleteLater')
    op.drop_table('deleteLater')
    op.alter_column('ai_requests', 'error_detail',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_ai_requests_started_at'), table_name='ai_requests')
    op.drop_index(op.f('idx_ai_requests_tenant_id'), table_name='ai_requests')
    op.alter_column('ai_services', 'provider_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_ai_services_service_id'), 'ai_services', ['service_id'], unique=False)
    op.alter_column('intent_mapping_audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('intent_mapping_audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_intent_mapping_audit_logs_id'), 'intent_mapping_audit_logs', ['id'], unique=False)
    op.drop_index(op.f('idx_intent_routing_intent_name'), table_name='intent_routing')
    op.drop_constraint(op.f('intent_routing_intent_name_key'), 'intent_routing', type_='unique')
    op.create_index(op.f('ix_intent_routing_id'), 'intent_routing', ['id'], unique=False)
    op.create_index(op.f('ix_intent_routing_intent_name'), 'intent_routing', ['intent_name'], unique=True)
    op.alter_column('permission_audit_logs', 'performed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('permission_audit_logs', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_permission_audit_logs_id'), 'permission_audit_logs', ['id'], unique=False)
    op.alter_column('policy_evaluation_audit_logs', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_policy_audit_request_id'), table_name='policy_evaluation_audit_logs')
    op.create_index(op.f('ix_policy_evaluation_audit_logs_id'), 'policy_evaluation_audit_logs', ['id'], unique=False)
    op.alter_column('tenant_service_permissions', 'granted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_service_permissions', 'granted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_policy_evaluation_audit_logs_id'), table_name='policy_evaluation_audit_logs')
    op.create_index(op.f('idx_policy_audit_request_id'), 'policy_evaluation_audit_logs', ['request_id'], unique=False)
    op.alter_column('policy_evaluation_audit_logs', 'context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_permission_audit_logs_id'), table_name='permission_audit_logs')
    op.alter_column('permission_audit_logs', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('permission_audit_logs', 'performed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_intent_routing_intent_name'), table_name='intent_routing')
    op.drop_index(op.f('ix_intent_routing_id'), table_name='intent_routing')
    op.create_unique_constraint(op.f('intent_routing_intent_name_key'), 'intent_routing', ['intent_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_intent_routing_intent_name'), 'intent_routing', ['intent_name'], unique=False)
    op.drop_index(op.f('ix_intent_mapping_audit_logs_id'), table_name='intent_mapping_audit_logs')
    op.alter_column('intent_mapping_audit_logs', 'new_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('intent_mapping_audit_logs', 'old_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_services_service_id'), table_name='ai_services')
    op.alter_column('ai_services', 'provider_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_ai_requests_tenant_id'), 'ai_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_ai_requests_started_at'), 'ai_requests', ['started_at'], unique=False)
    op.alter_column('ai_requests', 'error_detail',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('deleteLater',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('deleteLater_pkey'))
    )
    op.create_index(op.f('ix_deleteLater_name'), 'deleteLater', ['name'], unique=False)
    op.create_index(op.f('ix_deleteLater_id'), 'deleteLater', ['id'], unique=False)
    op.create_index(op.f('ix_deleteLater_description'), 'deleteLater', ['description'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    op.create_index(op.f('ix_questions_question_text'), 'questions', ['question_text'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('choices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('choice_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('choices_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('choices_pkey'))
    )
    op.create_index(op.f('ix_choices_id'), 'choices', ['id'], unique=False)
    op.create_index(op.f('ix_choices_choice_text'), 'choices', ['choice_text'], unique=False)
    op.drop_table('governance_policies')
    # ### end Alembic commands ###
