apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: "prometheus_ds_id"
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PlatformDB
    type: postgres
    uid: "platform_db_ds_id"
    url: platform-db:5432
    user: platform_admin
    secureJsonData:
      password: platform_pass
    jsonData:
      database: platform_permissions
      sslmode: 'disable'
      postgresVersion: 15
      timescaleDB: false
